version: 1

formatters:
  standard:
    format: '[%(asctime)s] [%(levelname)s] %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  infoFile_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: ./info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  errorFile_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: standard
    filename: ./errors.log
    backupCount: 20
    encoding: utf8

loggers:
  infoLogger:
    level: INFO
    handlers: [console, infoFile_handler]
    propagate: False

  errorLogger:
    level: ERROR
    handlers: [console, errorFile_handler]
    propagate: False